name: Build APK from ZIP

on:
  workflow_dispatch:
  push:
    paths:
      - 'project.zip'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip project
        run: unzip -o project.zip -d .

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          sdkmanager --install "platform-tools" "build-tools;34.0.0" "platforms;android-34"

      - name: Set up Gradle 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.7'
          cache-disabled: true

      - name: Build release APK
        run: |
          gradle -v
          gradle :app:assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CarMode-release-apk
          path: app/build/outputs/apk/release/*.apk
